In [1]:
import importlib
import matplotlib.pyplot as plt
import numpy as np
import pickle
from multiprocessing import Pool, cpu_count

In [2]:
from utils.tree_search import Node, Queue, Stack, Tree
import shelfsolver

In [3]:
importlib.reload(shelfsolver)

<module 'shelfsolver' from 'D:\\projects\\ErgoVR\\code\\shelf-solver-master\\shelfsolver.py'>

# Tasks

1. Sort object so that each row has only objects of one color

2a. Sort objects so that each row has all the unique colors and all the unique shapes once 

2b. Sort objects so that each column has all the unique colors and all the unique shapes once 

3a. Sort objects so that each row and column has each of the four colors once. ← this task can take longer and may have longer duration than preceding tasks 

3b. Sort objects so that each row and column has each of the four shapes once. ← this task can take longer and may have longer duration than preceding tasks 

## Task 1: One color per row

### Solve single shelf

In [4]:
solver = shelfsolver.ShelfSolver()
shelf = shelfsolver.ShelfGenerator().new_random_shelf()
print(shelf)

[[11 24 41  0 34]
 [33 44 31  0  0]
 [43  0 13 32  0]
 [ 0 21 42 14 12]
 [ 0  0  0 23 22]]


In [5]:
result = solver.solve_task(shelf, task=1, verbose=1, search_type="stack")
result

(array([[ 0, 44, 41, 42, 43],
        [33,  0, 31, 34, 32],
        [ 0,  0,  0,  0,  0],
        [ 0, 11, 13, 14, 12],
        [ 0, 24, 21, 23, 22]]),
 9)

## Task 2: Every row should contain items of unique color and shape

In [6]:
solver = shelfsolver.ShelfSolver()
shelf = shelfsolver.ShelfGenerator().new_random_shelf()
print(shelf)

[[31  0 34 42 11]
 [ 0 21  0 33  0]
 [13  0 12  0 41]
 [43  0 14 22 23]
 [ 0  0 44 24 32]]


In [7]:
result = solver.solve_task(shelf, task=2, verbose=1, search_type="stack", collect=False)
result

Current score: 42 | Depth: 6 | Length of tree: 29
Solution found!


(array([[ 0, 23, 34, 42, 11],
        [ 0,  0,  0,  0,  0],
        [33, 24, 12,  0, 41],
        [43, 31, 14, 22,  0],
        [13, 21, 44,  0, 32]]),
 7)

## Task 3: Each row and each column has each of the four colors once.

In [8]:
solver = shelfsolver.ShelfSolver()
shelf = shelfsolver.ShelfGenerator().new_random_shelf()
print(shelf)

[[31 32 14 33 24]
 [ 0 44 13 23  0]
 [ 0 41  0  0  0]
 [34 21  0 42 11]
 [22 43 12  0  0]]


In [9]:
result = solver.solve_task(shelf, task=3, verbose=1, search_type="stack", collect=False)
result

Current score: 51 | Depth: 16 | Length of tree: 109
Solution found!


(array([[31, 44, 13,  0, 24],
        [21, 14, 33,  0, 41],
        [12, 23, 43,  0, 34],
        [42, 32, 22,  0, 11],
        [ 0,  0,  0,  0,  0]]),
 17)